datasource:
  url: tcp(localhost:3306)/mall?charset=utf8mb4&parseTime=True&loc=Local
  username: root
  password: password
redis:
  addr: localhost:6379
  password:
mongo:
  url: localhost:27017
  username: root
  password: password
rabbit:
  url: localhost:5672
  username: guest
  password: guest