datasource:
  url: tcp(127.0.0.1:3306)/mall?charset=utf8mb4&parseTime=True&loc=Local
  username: root
  password: password
redis:
  addr: 127.0.0.1:6379
  password:
mongo:
  url: 127.0.0.1:27017
  username: root
  password: password