// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsBrand = "pms_brand"

// PmsBrand mapped from table <pms_brand>
type PmsBrand struct {
	ID                  int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	Name                string `gorm:"column:name" json:"name" form:"name"`
	FirstLetter         string `gorm:"column:first_letter" json:"firstLetter" form:"firstLetter"` // 首字母
	Sort                int32  `gorm:"column:sort" json:"sort" form:"sort"`
	FactoryStatus       int32  `gorm:"column:factory_status" json:"factoryStatus" form:"factoryStatus"` // 是否为品牌制造商：0->不是；1->是
	ShowStatus          int32  `gorm:"column:show_status" json:"showStatus" form:"showStatus"`
	ProductCount        int32  `gorm:"column:product_count" json:"productCount" form:"productCount"`                       // 产品数量
	ProductCommentCount int32  `gorm:"column:product_comment_count" json:"productCommentCount" form:"productCommentCount"` // 产品评论数量
	Logo                string `gorm:"column:logo" json:"logo" form:"logo"`                                                // 品牌logo
	BigPic              string `gorm:"column:big_pic" json:"bigPic" form:"bigPic"`                                         // 专区大图
	BrandStory          string `gorm:"column:brand_story" json:"brandStory" form:"brandStory"`                             // 品牌故事
}

// TableName PmsBrand's table name
func (*PmsBrand) TableName() string {
	return TableNamePmsBrand
}
