// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePmsProductVertifyRecord = "pms_product_vertify_record"

// PmsProductVertifyRecord mapped from table <pms_product_vertify_record>
type PmsProductVertifyRecord struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProductID  int64     `gorm:"column:product_id" json:"product_id"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	VertifyMan string    `gorm:"column:vertify_man" json:"vertify_man"` // 审核人
	Status     int32     `gorm:"column:status" json:"status"`
	Detail     string    `gorm:"column:detail" json:"detail"` // 反馈详情
}

// TableName PmsProductVertifyRecord's table name
func (*PmsProductVertifyRecord) TableName() string {
	return TableNamePmsProductVertifyRecord
}
