// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsSkuStock = "pms_sku_stock"

// PmsSkuStock mapped from table <pms_sku_stock>
type PmsSkuStock struct {
	ID             int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	ProductID      int64   `gorm:"column:product_id" json:"productId" form:"productId"`
	SkuCode        string  `gorm:"column:sku_code;not null" json:"skuCode" form:"skuCode"` // sku编码
	Price          float64 `gorm:"column:price" json:"price" form:"price"`
	Stock          int32   `gorm:"column:stock" json:"stock" form:"stock"`                             // 库存
	LowStock       int32   `gorm:"column:low_stock" json:"lowStock" form:"lowStock"`                   // 预警库存
	Pic            string  `gorm:"column:pic" json:"pic" form:"pic"`                                   // 展示图片
	Sale           int32   `gorm:"column:sale" json:"sale" form:"sale"`                                // 销量
	PromotionPrice float64 `gorm:"column:promotion_price" json:"promotionPrice" form:"promotionPrice"` // 单品促销价格
	LockStock      int32   `gorm:"column:lock_stock" json:"lockStock" form:"lockStock"`                // 锁定库存
	SpData         string  `gorm:"column:sp_data" json:"spData" form:"spData"`                         // 商品销售属性，json格式
}

// TableName PmsSkuStock's table name
func (*PmsSkuStock) TableName() string {
	return TableNamePmsSkuStock
}
