// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsProductAttributeCategory = "pms_product_attribute_category"

// PmsProductAttributeCategory mapped from table <pms_product_attribute_category>
type PmsProductAttributeCategory struct {
	ID             int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	Name           string `gorm:"column:name" json:"name" form:"name"`
	AttributeCount int32  `gorm:"column:attribute_count" json:"attributeCount" form:"attributeCount"` // 属性数量
	ParamCount     int32  `gorm:"column:param_count" json:"paramCount" form:"paramCount"`             // 参数数量
}

// TableName PmsProductAttributeCategory's table name
func (*PmsProductAttributeCategory) TableName() string {
	return TableNamePmsProductAttributeCategory
}
