// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsProductAttributeValue = "pms_product_attribute_value"

// PmsProductAttributeValue mapped from table <pms_product_attribute_value>
type PmsProductAttributeValue struct {
	ID                 int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	ProductID          int64  `gorm:"column:product_id" json:"productId" form:"productId"`
	ProductAttributeID int64  `gorm:"column:product_attribute_id" json:"productAttributeId" form:"productAttributeId"`
	Value              string `gorm:"column:value" json:"value" form:"value"` // 手动添加规格或参数的值，参数单值，规格有多个时以逗号隔开
}

// TableName PmsProductAttributeValue's table name
func (*PmsProductAttributeValue) TableName() string {
	return TableNamePmsProductAttributeValue
}
