// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePmsProduct = "pms_product"

// PmsProduct mapped from table <pms_product>
type PmsProduct struct {
	ID                         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	BrandID                    int64     `gorm:"column:brand_id" json:"brandId" form:"brandId"`
	ProductCategoryID          int64     `gorm:"column:product_category_id" json:"productCategoryId" form:"productCategoryId"`
	FeightTemplateID           int64     `gorm:"column:feight_template_id" json:"feightTemplateId" form:"feightTemplateId"`
	ProductAttributeCategoryID int64     `gorm:"column:product_attribute_category_id" json:"productAttributeCategoryId" form:"productAttributeCategoryId"`
	Name                       string    `gorm:"column:name;not null" json:"name" form:"name"`
	Pic                        string    `gorm:"column:pic" json:"pic" form:"pic"`
	ProductSn                  string    `gorm:"column:product_sn;not null" json:"productSn" form:"productSn"`          // 货号
	DeleteStatus               int32     `gorm:"column:delete_status" json:"deleteStatus" form:"deleteStatus"`          // 删除状态：0->未删除；1->已删除
	PublishStatus              int32     `gorm:"column:publish_status" json:"publishStatus" form:"publishStatus"`       // 上架状态：0->下架；1->上架
	NewStatus                  int32     `gorm:"column:new_status" json:"newStatus" form:"newStatus"`                   // 新品状态:0->不是新品；1->新品
	RecommandStatus            int32     `gorm:"column:recommand_status" json:"recommandStatus" form:"recommandStatus"` // 推荐状态；0->不推荐；1->推荐
	VerifyStatus               int32     `gorm:"column:verify_status" json:"verifyStatus" form:"verifyStatus"`          // 审核状态：0->未审核；1->审核通过
	Sort                       int32     `gorm:"column:sort" json:"sort" form:"sort"`                                   // 排序
	Sale                       int32     `gorm:"column:sale" json:"sale" form:"sale"`                                   // 销量
	Price                      float64   `gorm:"column:price" json:"price" form:"price"`
	PromotionPrice             float64   `gorm:"column:promotion_price" json:"promotionPrice" form:"promotionPrice"` // 促销价格
	GiftGrowth                 int32     `gorm:"column:gift_growth" json:"giftGrowth" form:"giftGrowth"`             // 赠送的成长值
	GiftPoint                  int32     `gorm:"column:gift_point" json:"giftPoint" form:"giftPoint"`                // 赠送的积分
	UsePointLimit              int32     `gorm:"column:use_point_limit" json:"usePointLimit" form:"usePointLimit"`   // 限制使用的积分数
	SubTitle                   string    `gorm:"column:sub_title" json:"subTitle" form:"subTitle"`                   // 副标题
	Description                string    `gorm:"column:description" json:"description" form:"description"`           // 商品描述
	OriginalPrice              float64   `gorm:"column:original_price" json:"originalPrice" form:"originalPrice"`    // 市场价
	Stock                      int32     `gorm:"column:stock" json:"stock" form:"stock"`                             // 库存
	LowStock                   int32     `gorm:"column:low_stock" json:"lowStock" form:"lowStock"`                   // 库存预警值
	Unit                       string    `gorm:"column:unit" json:"unit" form:"unit"`                                // 单位
	Weight                     float64   `gorm:"column:weight" json:"weight" form:"weight"`                          // 商品重量，默认为克
	PreviewStatus              int32     `gorm:"column:preview_status" json:"previewStatus" form:"previewStatus"`    // 是否为预告商品：0->不是；1->是
	ServiceIds                 string    `gorm:"column:service_ids" json:"serviceIds" form:"serviceIds"`             // 以逗号分割的产品服务：1->无忧退货；2->快速退款；3->免费包邮
	Keywords                   string    `gorm:"column:keywords" json:"keywords" form:"keywords"`
	Note                       string    `gorm:"column:note" json:"note" form:"note"`
	AlbumPics                  string    `gorm:"column:album_pics" json:"albumPics" form:"albumPics"` // 画册图片，连产品图片限制为5张，以逗号分割
	DetailTitle                string    `gorm:"column:detail_title" json:"detailTitle" form:"detailTitle"`
	DetailDesc                 string    `gorm:"column:detail_desc" json:"detailDesc" form:"detailDesc"`
	DetailHTML                 string    `gorm:"column:detail_html" json:"detailHtml" form:"detailHtml"`                             // 产品详情网页内容
	DetailMobileHTML           string    `gorm:"column:detail_mobile_html" json:"detailMobileHtml" form:"detailMobileHtml"`          // 移动端网页详情
	PromotionStartTime         time.Time `gorm:"column:promotion_start_time" json:"promotionStartTime" form:"promotionStartTime"`    // 促销开始时间
	PromotionEndTime           time.Time `gorm:"column:promotion_end_time" json:"promotionEndTime" form:"promotionEndTime"`          // 促销结束时间
	PromotionPerLimit          int32     `gorm:"column:promotion_per_limit" json:"promotionPerLimit" form:"promotionPerLimit"`       // 活动限购数量
	PromotionType              int32     `gorm:"column:promotion_type" json:"promotionType" form:"promotionType"`                    // 促销类型：0->没有促销使用原价;1->使用促销价；2->使用会员价；3->使用阶梯价格；4->使用满减价格；5->限时购
	BrandName                  string    `gorm:"column:brand_name" json:"brandName" form:"brandName"`                                // 品牌名称
	ProductCategoryName        string    `gorm:"column:product_category_name" json:"productCategoryName" form:"productCategoryName"` // 商品分类名称
}

// TableName PmsProduct's table name
func (*PmsProduct) TableName() string {
	return TableNamePmsProduct
}
