// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsProductLadder = "pms_product_ladder"

// PmsProductLadder mapped from table <pms_product_ladder>
type PmsProductLadder struct {
	ID        int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	ProductID int64   `gorm:"column:product_id" json:"productId" form:"productId"`
	Count_    int32   `gorm:"column:count" json:"count" form:"count"`          // 满足的商品数量
	Discount  float64 `gorm:"column:discount" json:"discount" form:"discount"` // 折扣
	Price     float64 `gorm:"column:price" json:"price" form:"price"`          // 折后价格
}

// TableName PmsProductLadder's table name
func (*PmsProductLadder) TableName() string {
	return TableNamePmsProductLadder
}
