// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsMemberPrice = "pms_member_price"

// PmsMemberPrice mapped from table <pms_member_price>
type PmsMemberPrice struct {
	ID              int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	ProductID       int64   `gorm:"column:product_id" json:"productId" form:"productId"`
	MemberLevelID   int64   `gorm:"column:member_level_id" json:"memberLevelId" form:"memberLevelId"`
	MemberPrice     float64 `gorm:"column:member_price" json:"memberPrice" form:"memberPrice"` // 会员价格
	MemberLevelName string  `gorm:"column:member_level_name" json:"memberLevelName" form:"memberLevelName"`
}

// TableName PmsMemberPrice's table name
func (*PmsMemberPrice) TableName() string {
	return TableNamePmsMemberPrice
}
