// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUmsRoleResourceRelation = "ums_role_resource_relation"

// UmsRoleResourceRelation mapped from table <ums_role_resource_relation>
type UmsRoleResourceRelation struct {
	ID         int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	RoleID     int64 `gorm:"column:role_id" json:"roleId" form:"roleId"`             // 角色ID
	ResourceID int64 `gorm:"column:resource_id" json:"resourceId" form:"resourceId"` // 资源ID
}

// TableName UmsRoleResourceRelation's table name
func (*UmsRoleResourceRelation) TableName() string {
	return TableNameUmsRoleResourceRelation
}
