// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUmsAdmin = "ums_admin"

// UmsAdmin mapped from table <ums_admin>
type UmsAdmin struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	Username   string    `gorm:"column:username" json:"username" form:"username"`
	Password   string    `gorm:"column:password" json:"password" form:"password"`
	Icon       string    `gorm:"column:icon" json:"icon" form:"icon"`                    // 头像
	Email      string    `gorm:"column:email" json:"email" form:"email"`                 // 邮箱
	NickName   string    `gorm:"column:nick_name" json:"nickName" form:"nickName"`       // 昵称
	Note       string    `gorm:"column:note" json:"note" form:"note"`                    // 备注信息
	CreateTime time.Time `gorm:"column:create_time" json:"createTime" form:"createTime"` // 创建时间
	LoginTime  time.Time `gorm:"column:login_time" json:"loginTime" form:"loginTime"`    // 最后登录时间
	Status     int32     `gorm:"column:status;default:1" json:"status" form:"status"`    // 帐号启用状态：0->禁用；1->启用
}

// TableName UmsAdmin's table name
func (*UmsAdmin) TableName() string {
	return TableNameUmsAdmin
}
