// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUmsRole = "ums_role"

// UmsRole mapped from table <ums_role>
type UmsRole struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	Name        string    `gorm:"column:name" json:"name" form:"name"`                      // 名称
	Description string    `gorm:"column:description" json:"description" form:"description"` // 描述
	AdminCount  int32     `gorm:"column:admin_count" json:"adminCount" form:"adminCount"`   // 后台用户数量
	CreateTime  time.Time `gorm:"column:create_time" json:"createTime" form:"createTime"`   // 创建时间
	Status      int32     `gorm:"column:status;default:1" json:"status" form:"status"`      // 启用状态：0->禁用；1->启用
	Sort        int32     `gorm:"column:sort" json:"sort" form:"sort"`
}

// TableName UmsRole's table name
func (*UmsRole) TableName() string {
	return TableNameUmsRole
}
