// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUmsMenu = "ums_menu"

// UmsMenu mapped from table <ums_menu>
type UmsMenu struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	ParentID   int64     `gorm:"column:parent_id" json:"parentId" form:"parentId"`       // 父级ID
	CreateTime time.Time `gorm:"column:create_time" json:"createTime" form:"createTime"` // 创建时间
	Title      string    `gorm:"column:title" json:"title" form:"title"`                 // 菜单名称
	Level      int32     `gorm:"column:level" json:"level" form:"level"`                 // 菜单级数
	Sort       int32     `gorm:"column:sort" json:"sort" form:"sort"`                    // 菜单排序
	Name       string    `gorm:"column:name" json:"name" form:"name"`                    // 前端名称
	Icon       string    `gorm:"column:icon" json:"icon" form:"icon"`                    // 前端图标
	Hidden     int32     `gorm:"column:hidden" json:"hidden" form:"hidden"`              // 前端隐藏
}

// TableName UmsMenu's table name
func (*UmsMenu) TableName() string {
	return TableNameUmsMenu
}
