// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUmsResource = "ums_resource"

// UmsResource mapped from table <ums_resource>
type UmsResource struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	CreateTime  time.Time `gorm:"column:create_time" json:"createTime" form:"createTime"`   // 创建时间
	Name        string    `gorm:"column:name" json:"name" form:"name"`                      // 资源名称
	URL         string    `gorm:"column:url" json:"url" form:"url"`                         // 资源URL
	Description string    `gorm:"column:description" json:"description" form:"description"` // 描述
	CategoryID  int64     `gorm:"column:category_id" json:"categoryId" form:"categoryId"`   // 资源分类ID
}

// TableName UmsResource's table name
func (*UmsResource) TableName() string {
	return TableNameUmsResource
}
