// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUmsAdminRoleRelation = "ums_admin_role_relation"

// UmsAdminRoleRelation mapped from table <ums_admin_role_relation>
type UmsAdminRoleRelation struct {
	ID      int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	AdminID int64 `gorm:"column:admin_id" json:"adminId" form:"adminId"`
	RoleID  int64 `gorm:"column:role_id" json:"roleId" form:"roleId"`
}

// TableName UmsAdminRoleRelation's table name
func (*UmsAdminRoleRelation) TableName() string {
	return TableNameUmsAdminRoleRelation
}
