// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUmsRoleMenuRelation = "ums_role_menu_relation"

// UmsRoleMenuRelation mapped from table <ums_role_menu_relation>
type UmsRoleMenuRelation struct {
	ID     int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	RoleID int64 `gorm:"column:role_id" json:"roleId" form:"roleId"` // 角色ID
	MenuID int64 `gorm:"column:menu_id" json:"menuId" form:"menuId"` // 菜单ID
}

// TableName UmsRoleMenuRelation's table name
func (*UmsRoleMenuRelation) TableName() string {
	return TableNameUmsRoleMenuRelation
}
