// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

var (
	Q                                = new(Query)
	SmsCoupon                        *smsCoupon
	SmsCouponHistory                 *smsCouponHistory
	SmsCouponProductCategoryRelation *smsCouponProductCategoryRelation
	SmsCouponProductRelation         *smsCouponProductRelation
	SmsFlashPromotion                *smsFlashPromotion
	SmsFlashPromotionProductRelation *smsFlashPromotionProductRelation
	SmsFlashPromotionSession         *smsFlashPromotionSession
	SmsHomeAdvertise                 *smsHomeAdvertise
	SmsHomeBrand                     *smsHomeBrand
	SmsHomeNewProduct                *smsHomeNewProduct
	SmsHomeRecommendProduct          *smsHomeRecommendProduct
	SmsHomeRecommendSubject          *smsHomeRecommendSubject
)

func SetDefault(db *gorm.DB) {
	*Q = *Use(db)
	SmsCoupon = &Q.SmsCoupon
	SmsCouponHistory = &Q.SmsCouponHistory
	SmsCouponProductCategoryRelation = &Q.SmsCouponProductCategoryRelation
	SmsCouponProductRelation = &Q.SmsCouponProductRelation
	SmsFlashPromotion = &Q.SmsFlashPromotion
	SmsFlashPromotionProductRelation = &Q.SmsFlashPromotionProductRelation
	SmsFlashPromotionSession = &Q.SmsFlashPromotionSession
	SmsHomeAdvertise = &Q.SmsHomeAdvertise
	SmsHomeBrand = &Q.SmsHomeBrand
	SmsHomeNewProduct = &Q.SmsHomeNewProduct
	SmsHomeRecommendProduct = &Q.SmsHomeRecommendProduct
	SmsHomeRecommendSubject = &Q.SmsHomeRecommendSubject
}

func Use(db *gorm.DB) *Query {
	return &Query{
		db:                               db,
		SmsCoupon:                        newSmsCoupon(db),
		SmsCouponHistory:                 newSmsCouponHistory(db),
		SmsCouponProductCategoryRelation: newSmsCouponProductCategoryRelation(db),
		SmsCouponProductRelation:         newSmsCouponProductRelation(db),
		SmsFlashPromotion:                newSmsFlashPromotion(db),
		SmsFlashPromotionProductRelation: newSmsFlashPromotionProductRelation(db),
		SmsFlashPromotionSession:         newSmsFlashPromotionSession(db),
		SmsHomeAdvertise:                 newSmsHomeAdvertise(db),
		SmsHomeBrand:                     newSmsHomeBrand(db),
		SmsHomeNewProduct:                newSmsHomeNewProduct(db),
		SmsHomeRecommendProduct:          newSmsHomeRecommendProduct(db),
		SmsHomeRecommendSubject:          newSmsHomeRecommendSubject(db),
	}
}

type Query struct {
	db *gorm.DB

	SmsCoupon                        smsCoupon
	SmsCouponHistory                 smsCouponHistory
	SmsCouponProductCategoryRelation smsCouponProductCategoryRelation
	SmsCouponProductRelation         smsCouponProductRelation
	SmsFlashPromotion                smsFlashPromotion
	SmsFlashPromotionProductRelation smsFlashPromotionProductRelation
	SmsFlashPromotionSession         smsFlashPromotionSession
	SmsHomeAdvertise                 smsHomeAdvertise
	SmsHomeBrand                     smsHomeBrand
	SmsHomeNewProduct                smsHomeNewProduct
	SmsHomeRecommendProduct          smsHomeRecommendProduct
	SmsHomeRecommendSubject          smsHomeRecommendSubject
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                               db,
		SmsCoupon:                        q.SmsCoupon.clone(db),
		SmsCouponHistory:                 q.SmsCouponHistory.clone(db),
		SmsCouponProductCategoryRelation: q.SmsCouponProductCategoryRelation.clone(db),
		SmsCouponProductRelation:         q.SmsCouponProductRelation.clone(db),
		SmsFlashPromotion:                q.SmsFlashPromotion.clone(db),
		SmsFlashPromotionProductRelation: q.SmsFlashPromotionProductRelation.clone(db),
		SmsFlashPromotionSession:         q.SmsFlashPromotionSession.clone(db),
		SmsHomeAdvertise:                 q.SmsHomeAdvertise.clone(db),
		SmsHomeBrand:                     q.SmsHomeBrand.clone(db),
		SmsHomeNewProduct:                q.SmsHomeNewProduct.clone(db),
		SmsHomeRecommendProduct:          q.SmsHomeRecommendProduct.clone(db),
		SmsHomeRecommendSubject:          q.SmsHomeRecommendSubject.clone(db),
	}
}

type queryCtx struct {
	SmsCoupon                        *smsCouponDo
	SmsCouponHistory                 *smsCouponHistoryDo
	SmsCouponProductCategoryRelation *smsCouponProductCategoryRelationDo
	SmsCouponProductRelation         *smsCouponProductRelationDo
	SmsFlashPromotion                *smsFlashPromotionDo
	SmsFlashPromotionProductRelation *smsFlashPromotionProductRelationDo
	SmsFlashPromotionSession         *smsFlashPromotionSessionDo
	SmsHomeAdvertise                 *smsHomeAdvertiseDo
	SmsHomeBrand                     *smsHomeBrandDo
	SmsHomeNewProduct                *smsHomeNewProductDo
	SmsHomeRecommendProduct          *smsHomeRecommendProductDo
	SmsHomeRecommendSubject          *smsHomeRecommendSubjectDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		SmsCoupon:                        q.SmsCoupon.WithContext(ctx),
		SmsCouponHistory:                 q.SmsCouponHistory.WithContext(ctx),
		SmsCouponProductCategoryRelation: q.SmsCouponProductCategoryRelation.WithContext(ctx),
		SmsCouponProductRelation:         q.SmsCouponProductRelation.WithContext(ctx),
		SmsFlashPromotion:                q.SmsFlashPromotion.WithContext(ctx),
		SmsFlashPromotionProductRelation: q.SmsFlashPromotionProductRelation.WithContext(ctx),
		SmsFlashPromotionSession:         q.SmsFlashPromotionSession.WithContext(ctx),
		SmsHomeAdvertise:                 q.SmsHomeAdvertise.WithContext(ctx),
		SmsHomeBrand:                     q.SmsHomeBrand.WithContext(ctx),
		SmsHomeNewProduct:                q.SmsHomeNewProduct.WithContext(ctx),
		SmsHomeRecommendProduct:          q.SmsHomeRecommendProduct.WithContext(ctx),
		SmsHomeRecommendSubject:          q.SmsHomeRecommendSubject.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
