// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall-admin-server/sms/model"
)

func newSmsCouponProductCategoryRelation(db *gorm.DB) smsCouponProductCategoryRelation {
	_smsCouponProductCategoryRelation := smsCouponProductCategoryRelation{}

	_smsCouponProductCategoryRelation.smsCouponProductCategoryRelationDo.UseDB(db)
	_smsCouponProductCategoryRelation.smsCouponProductCategoryRelationDo.UseModel(&model.SmsCouponProductCategoryRelation{})

	tableName := _smsCouponProductCategoryRelation.smsCouponProductCategoryRelationDo.TableName()
	_smsCouponProductCategoryRelation.ALL = field.NewField(tableName, "*")
	_smsCouponProductCategoryRelation.ID = field.NewInt64(tableName, "id")
	_smsCouponProductCategoryRelation.CouponID = field.NewInt64(tableName, "coupon_id")
	_smsCouponProductCategoryRelation.ProductCategoryID = field.NewInt64(tableName, "product_category_id")
	_smsCouponProductCategoryRelation.ProductCategoryName = field.NewString(tableName, "product_category_name")
	_smsCouponProductCategoryRelation.ParentCategoryName = field.NewString(tableName, "parent_category_name")

	_smsCouponProductCategoryRelation.fillFieldMap()

	return _smsCouponProductCategoryRelation
}

type smsCouponProductCategoryRelation struct {
	smsCouponProductCategoryRelationDo

	ALL                 field.Field
	ID                  field.Int64
	CouponID            field.Int64
	ProductCategoryID   field.Int64
	ProductCategoryName field.String
	ParentCategoryName  field.String

	fieldMap map[string]field.Expr
}

func (s smsCouponProductCategoryRelation) Table(newTableName string) *smsCouponProductCategoryRelation {
	s.smsCouponProductCategoryRelationDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s smsCouponProductCategoryRelation) As(alias string) *smsCouponProductCategoryRelation {
	s.smsCouponProductCategoryRelationDo.DO = *(s.smsCouponProductCategoryRelationDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *smsCouponProductCategoryRelation) updateTableName(table string) *smsCouponProductCategoryRelation {
	s.ALL = field.NewField(table, "*")
	s.ID = field.NewInt64(table, "id")
	s.CouponID = field.NewInt64(table, "coupon_id")
	s.ProductCategoryID = field.NewInt64(table, "product_category_id")
	s.ProductCategoryName = field.NewString(table, "product_category_name")
	s.ParentCategoryName = field.NewString(table, "parent_category_name")

	s.fillFieldMap()

	return s
}

func (s *smsCouponProductCategoryRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *smsCouponProductCategoryRelation) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["id"] = s.ID
	s.fieldMap["coupon_id"] = s.CouponID
	s.fieldMap["product_category_id"] = s.ProductCategoryID
	s.fieldMap["product_category_name"] = s.ProductCategoryName
	s.fieldMap["parent_category_name"] = s.ParentCategoryName
}

func (s smsCouponProductCategoryRelation) clone(db *gorm.DB) smsCouponProductCategoryRelation {
	s.smsCouponProductCategoryRelationDo.ReplaceDB(db)
	return s
}

type smsCouponProductCategoryRelationDo struct{ gen.DO }

func (s smsCouponProductCategoryRelationDo) Debug() *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Debug())
}

func (s smsCouponProductCategoryRelationDo) WithContext(ctx context.Context) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s smsCouponProductCategoryRelationDo) ReadDB() *smsCouponProductCategoryRelationDo {
	return s.Clauses(dbresolver.Read)
}

func (s smsCouponProductCategoryRelationDo) WriteDB() *smsCouponProductCategoryRelationDo {
	return s.Clauses(dbresolver.Write)
}

func (s smsCouponProductCategoryRelationDo) Clauses(conds ...clause.Expression) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s smsCouponProductCategoryRelationDo) Returning(value interface{}, columns ...string) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s smsCouponProductCategoryRelationDo) Not(conds ...gen.Condition) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s smsCouponProductCategoryRelationDo) Or(conds ...gen.Condition) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s smsCouponProductCategoryRelationDo) Select(conds ...field.Expr) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s smsCouponProductCategoryRelationDo) Where(conds ...gen.Condition) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s smsCouponProductCategoryRelationDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *smsCouponProductCategoryRelationDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s smsCouponProductCategoryRelationDo) Order(conds ...field.Expr) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s smsCouponProductCategoryRelationDo) Distinct(cols ...field.Expr) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s smsCouponProductCategoryRelationDo) Omit(cols ...field.Expr) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s smsCouponProductCategoryRelationDo) Join(table schema.Tabler, on ...field.Expr) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s smsCouponProductCategoryRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s smsCouponProductCategoryRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s smsCouponProductCategoryRelationDo) Group(cols ...field.Expr) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s smsCouponProductCategoryRelationDo) Having(conds ...gen.Condition) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s smsCouponProductCategoryRelationDo) Limit(limit int) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s smsCouponProductCategoryRelationDo) Offset(offset int) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s smsCouponProductCategoryRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s smsCouponProductCategoryRelationDo) Unscoped() *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Unscoped())
}

func (s smsCouponProductCategoryRelationDo) Create(values ...*model.SmsCouponProductCategoryRelation) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s smsCouponProductCategoryRelationDo) CreateInBatches(values []*model.SmsCouponProductCategoryRelation, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s smsCouponProductCategoryRelationDo) Save(values ...*model.SmsCouponProductCategoryRelation) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s smsCouponProductCategoryRelationDo) First() (*model.SmsCouponProductCategoryRelation, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmsCouponProductCategoryRelation), nil
	}
}

func (s smsCouponProductCategoryRelationDo) Take() (*model.SmsCouponProductCategoryRelation, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmsCouponProductCategoryRelation), nil
	}
}

func (s smsCouponProductCategoryRelationDo) Last() (*model.SmsCouponProductCategoryRelation, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmsCouponProductCategoryRelation), nil
	}
}

func (s smsCouponProductCategoryRelationDo) Find() ([]*model.SmsCouponProductCategoryRelation, error) {
	result, err := s.DO.Find()
	return result.([]*model.SmsCouponProductCategoryRelation), err
}

func (s smsCouponProductCategoryRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SmsCouponProductCategoryRelation, err error) {
	buf := make([]*model.SmsCouponProductCategoryRelation, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s smsCouponProductCategoryRelationDo) FindInBatches(result *[]*model.SmsCouponProductCategoryRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s smsCouponProductCategoryRelationDo) Attrs(attrs ...field.AssignExpr) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s smsCouponProductCategoryRelationDo) Assign(attrs ...field.AssignExpr) *smsCouponProductCategoryRelationDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s smsCouponProductCategoryRelationDo) Joins(fields ...field.RelationField) *smsCouponProductCategoryRelationDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s smsCouponProductCategoryRelationDo) Preload(fields ...field.RelationField) *smsCouponProductCategoryRelationDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s smsCouponProductCategoryRelationDo) FirstOrInit() (*model.SmsCouponProductCategoryRelation, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmsCouponProductCategoryRelation), nil
	}
}

func (s smsCouponProductCategoryRelationDo) FirstOrCreate() (*model.SmsCouponProductCategoryRelation, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmsCouponProductCategoryRelation), nil
	}
}

func (s smsCouponProductCategoryRelationDo) FindByPage(offset int, limit int) (result []*model.SmsCouponProductCategoryRelation, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s smsCouponProductCategoryRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s smsCouponProductCategoryRelationDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s smsCouponProductCategoryRelationDo) Delete(models ...*model.SmsCouponProductCategoryRelation) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *smsCouponProductCategoryRelationDo) withDO(do gen.Dao) *smsCouponProductCategoryRelationDo {
	s.DO = *do.(*gen.DO)
	return s
}
