// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSmsCouponHistory = "sms_coupon_history"

// SmsCouponHistory mapped from table <sms_coupon_history>
type SmsCouponHistory struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	CouponID       int64     `gorm:"column:coupon_id" json:"couponId" form:"couponId"`
	MemberID       int64     `gorm:"column:member_id" json:"memberId" form:"memberId"`
	CouponCode     string    `gorm:"column:coupon_code" json:"couponCode" form:"couponCode"`
	MemberNickname string    `gorm:"column:member_nickname" json:"memberNickname" form:"memberNickname"` // 领取人昵称
	GetType        int32     `gorm:"column:get_type" json:"getType" form:"getType"`                      // 获取类型：0->后台赠送；1->主动获取
	CreateTime     time.Time `gorm:"column:create_time" json:"createTime" form:"createTime"`
	UseStatus      int32     `gorm:"column:use_status" json:"useStatus" form:"useStatus"` // 使用状态：0->未使用；1->已使用；2->已过期
	UseTime        time.Time `gorm:"column:use_time" json:"useTime" form:"useTime"`       // 使用时间
	OrderID        int64     `gorm:"column:order_id" json:"orderId" form:"orderId"`       // 订单编号
	OrderSn        string    `gorm:"column:order_sn" json:"orderSn" form:"orderSn"`       // 订单号码
}

// TableName SmsCouponHistory's table name
func (*SmsCouponHistory) TableName() string {
	return TableNameSmsCouponHistory
}
