// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSmsHomeRecommendSubject = "sms_home_recommend_subject"

// SmsHomeRecommendSubject mapped from table <sms_home_recommend_subject>
type SmsHomeRecommendSubject struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	SubjectID       int64  `gorm:"column:subject_id" json:"subjectId" form:"subjectId"`
	SubjectName     string `gorm:"column:subject_name" json:"subjectName" form:"subjectName"`
	RecommendStatus int32  `gorm:"column:recommend_status" json:"recommendStatus" form:"recommendStatus"`
	Sort            int32  `gorm:"column:sort" json:"sort" form:"sort"`
}

// TableName SmsHomeRecommendSubject's table name
func (*SmsHomeRecommendSubject) TableName() string {
	return TableNameSmsHomeRecommendSubject
}
