// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSmsHomeBrand = "sms_home_brand"

// SmsHomeBrand mapped from table <sms_home_brand>
type SmsHomeBrand struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	BrandID         int64  `gorm:"column:brand_id" json:"brandId" form:"brandId"`
	BrandName       string `gorm:"column:brand_name" json:"brandName" form:"brandName"`
	RecommendStatus int32  `gorm:"column:recommend_status" json:"recommendStatus" form:"recommendStatus"`
	Sort            int32  `gorm:"column:sort" json:"sort" form:"sort"`
}

// TableName SmsHomeBrand's table name
func (*SmsHomeBrand) TableName() string {
	return TableNameSmsHomeBrand
}
