// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSmsFlashPromotionSession = "sms_flash_promotion_session"

// SmsFlashPromotionSession mapped from table <sms_flash_promotion_session>
type SmsFlashPromotionSession struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"` // 编号
	Name       string    `gorm:"column:name" json:"name" form:"name"`                         // 场次名称
	StartTime  time.Time `gorm:"column:start_time" json:"startTime" form:"startTime"`         // 每日开始时间
	EndTime    time.Time `gorm:"column:end_time" json:"endTime" form:"endTime"`               // 每日结束时间
	Status     int32     `gorm:"column:status" json:"status" form:"status"`                   // 启用状态：0->不启用；1->启用
	CreateTime time.Time `gorm:"column:create_time" json:"createTime" form:"createTime"`      // 创建时间
}

// TableName SmsFlashPromotionSession's table name
func (*SmsFlashPromotionSession) TableName() string {
	return TableNameSmsFlashPromotionSession
}
