// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSmsHomeAdvertise = "sms_home_advertise"

// SmsHomeAdvertise mapped from table <sms_home_advertise>
type SmsHomeAdvertise struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	Name       string    `gorm:"column:name" json:"name" form:"name"`
	Type       int32     `gorm:"column:type" json:"type" form:"type"` // 轮播位置：0->PC首页轮播；1->app首页轮播
	Pic        string    `gorm:"column:pic" json:"pic" form:"pic"`
	StartTime  time.Time `gorm:"column:start_time" json:"startTime" form:"startTime"`
	EndTime    time.Time `gorm:"column:end_time" json:"endTime" form:"endTime"`
	Status     int32     `gorm:"column:status" json:"status" form:"status"`              // 上下线状态：0->下线；1->上线
	ClickCount int32     `gorm:"column:click_count" json:"clickCount" form:"clickCount"` // 点击数
	OrderCount int32     `gorm:"column:order_count" json:"orderCount" form:"orderCount"` // 下单数
	URL        string    `gorm:"column:url" json:"url" form:"url"`                       // 链接地址
	Note       string    `gorm:"column:note" json:"note" form:"note"`                    // 备注
	Sort       int32     `gorm:"column:sort" json:"sort" form:"sort"`                    // 排序
}

// TableName SmsHomeAdvertise's table name
func (*SmsHomeAdvertise) TableName() string {
	return TableNameSmsHomeAdvertise
}
