// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSmsHomeNewProduct = "sms_home_new_product"

// SmsHomeNewProduct mapped from table <sms_home_new_product>
type SmsHomeNewProduct struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	ProductID       int64  `gorm:"column:product_id" json:"productId" form:"productId"`
	ProductName     string `gorm:"column:product_name" json:"productName" form:"productName"`
	RecommendStatus int32  `gorm:"column:recommend_status" json:"recommendStatus" form:"recommendStatus"`
	Sort            int32  `gorm:"column:sort" json:"sort" form:"sort"`
}

// TableName SmsHomeNewProduct's table name
func (*SmsHomeNewProduct) TableName() string {
	return TableNameSmsHomeNewProduct
}
