// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSmsFlashPromotion = "sms_flash_promotion"

// SmsFlashPromotion mapped from table <sms_flash_promotion>
type SmsFlashPromotion struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	Title      string    `gorm:"column:title" json:"title" form:"title"`
	StartDate  time.Time `gorm:"column:start_date" json:"startDate" form:"startDate"`    // 开始日期
	EndDate    time.Time `gorm:"column:end_date" json:"endDate" form:"endDate"`          // 结束日期
	Status     int32     `gorm:"column:status" json:"status" form:"status"`              // 上下线状态
	CreateTime time.Time `gorm:"column:create_time" json:"createTime" form:"createTime"` // 秒杀时间段名称
}

// TableName SmsFlashPromotion's table name
func (*SmsFlashPromotion) TableName() string {
	return TableNameSmsFlashPromotion
}
