// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall-admin-server/cms/model"
)

func newCmsPrefrenceAreaProductRelation(db *gorm.DB) cmsPrefrenceAreaProductRelation {
	_cmsPrefrenceAreaProductRelation := cmsPrefrenceAreaProductRelation{}

	_cmsPrefrenceAreaProductRelation.cmsPrefrenceAreaProductRelationDo.UseDB(db)
	_cmsPrefrenceAreaProductRelation.cmsPrefrenceAreaProductRelationDo.UseModel(&model.CmsPrefrenceAreaProductRelation{})

	tableName := _cmsPrefrenceAreaProductRelation.cmsPrefrenceAreaProductRelationDo.TableName()
	_cmsPrefrenceAreaProductRelation.ALL = field.NewField(tableName, "*")
	_cmsPrefrenceAreaProductRelation.ID = field.NewInt64(tableName, "id")
	_cmsPrefrenceAreaProductRelation.PrefrenceAreaID = field.NewInt64(tableName, "prefrence_area_id")
	_cmsPrefrenceAreaProductRelation.ProductID = field.NewInt64(tableName, "product_id")

	_cmsPrefrenceAreaProductRelation.fillFieldMap()

	return _cmsPrefrenceAreaProductRelation
}

type cmsPrefrenceAreaProductRelation struct {
	cmsPrefrenceAreaProductRelationDo

	ALL             field.Field
	ID              field.Int64
	PrefrenceAreaID field.Int64
	ProductID       field.Int64

	fieldMap map[string]field.Expr
}

func (c cmsPrefrenceAreaProductRelation) Table(newTableName string) *cmsPrefrenceAreaProductRelation {
	c.cmsPrefrenceAreaProductRelationDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsPrefrenceAreaProductRelation) As(alias string) *cmsPrefrenceAreaProductRelation {
	c.cmsPrefrenceAreaProductRelationDo.DO = *(c.cmsPrefrenceAreaProductRelationDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsPrefrenceAreaProductRelation) updateTableName(table string) *cmsPrefrenceAreaProductRelation {
	c.ALL = field.NewField(table, "*")
	c.ID = field.NewInt64(table, "id")
	c.PrefrenceAreaID = field.NewInt64(table, "prefrence_area_id")
	c.ProductID = field.NewInt64(table, "product_id")

	c.fillFieldMap()

	return c
}

func (c *cmsPrefrenceAreaProductRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsPrefrenceAreaProductRelation) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["id"] = c.ID
	c.fieldMap["prefrence_area_id"] = c.PrefrenceAreaID
	c.fieldMap["product_id"] = c.ProductID
}

func (c cmsPrefrenceAreaProductRelation) clone(db *gorm.DB) cmsPrefrenceAreaProductRelation {
	c.cmsPrefrenceAreaProductRelationDo.ReplaceDB(db)
	return c
}

type cmsPrefrenceAreaProductRelationDo struct{ gen.DO }

func (c cmsPrefrenceAreaProductRelationDo) Debug() *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsPrefrenceAreaProductRelationDo) WithContext(ctx context.Context) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsPrefrenceAreaProductRelationDo) ReadDB() *cmsPrefrenceAreaProductRelationDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsPrefrenceAreaProductRelationDo) WriteDB() *cmsPrefrenceAreaProductRelationDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsPrefrenceAreaProductRelationDo) Clauses(conds ...clause.Expression) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsPrefrenceAreaProductRelationDo) Returning(value interface{}, columns ...string) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsPrefrenceAreaProductRelationDo) Not(conds ...gen.Condition) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsPrefrenceAreaProductRelationDo) Or(conds ...gen.Condition) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsPrefrenceAreaProductRelationDo) Select(conds ...field.Expr) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsPrefrenceAreaProductRelationDo) Where(conds ...gen.Condition) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsPrefrenceAreaProductRelationDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsPrefrenceAreaProductRelationDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsPrefrenceAreaProductRelationDo) Order(conds ...field.Expr) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsPrefrenceAreaProductRelationDo) Distinct(cols ...field.Expr) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsPrefrenceAreaProductRelationDo) Omit(cols ...field.Expr) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsPrefrenceAreaProductRelationDo) Join(table schema.Tabler, on ...field.Expr) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsPrefrenceAreaProductRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsPrefrenceAreaProductRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsPrefrenceAreaProductRelationDo) Group(cols ...field.Expr) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsPrefrenceAreaProductRelationDo) Having(conds ...gen.Condition) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsPrefrenceAreaProductRelationDo) Limit(limit int) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsPrefrenceAreaProductRelationDo) Offset(offset int) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsPrefrenceAreaProductRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsPrefrenceAreaProductRelationDo) Unscoped() *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsPrefrenceAreaProductRelationDo) Create(values ...*model.CmsPrefrenceAreaProductRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsPrefrenceAreaProductRelationDo) CreateInBatches(values []*model.CmsPrefrenceAreaProductRelation, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsPrefrenceAreaProductRelationDo) Save(values ...*model.CmsPrefrenceAreaProductRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsPrefrenceAreaProductRelationDo) First() (*model.CmsPrefrenceAreaProductRelation, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsPrefrenceAreaProductRelation), nil
	}
}

func (c cmsPrefrenceAreaProductRelationDo) Take() (*model.CmsPrefrenceAreaProductRelation, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsPrefrenceAreaProductRelation), nil
	}
}

func (c cmsPrefrenceAreaProductRelationDo) Last() (*model.CmsPrefrenceAreaProductRelation, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsPrefrenceAreaProductRelation), nil
	}
}

func (c cmsPrefrenceAreaProductRelationDo) Find() ([]*model.CmsPrefrenceAreaProductRelation, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsPrefrenceAreaProductRelation), err
}

func (c cmsPrefrenceAreaProductRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsPrefrenceAreaProductRelation, err error) {
	buf := make([]*model.CmsPrefrenceAreaProductRelation, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsPrefrenceAreaProductRelationDo) FindInBatches(result *[]*model.CmsPrefrenceAreaProductRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsPrefrenceAreaProductRelationDo) Attrs(attrs ...field.AssignExpr) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsPrefrenceAreaProductRelationDo) Assign(attrs ...field.AssignExpr) *cmsPrefrenceAreaProductRelationDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsPrefrenceAreaProductRelationDo) Joins(fields ...field.RelationField) *cmsPrefrenceAreaProductRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsPrefrenceAreaProductRelationDo) Preload(fields ...field.RelationField) *cmsPrefrenceAreaProductRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsPrefrenceAreaProductRelationDo) FirstOrInit() (*model.CmsPrefrenceAreaProductRelation, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsPrefrenceAreaProductRelation), nil
	}
}

func (c cmsPrefrenceAreaProductRelationDo) FirstOrCreate() (*model.CmsPrefrenceAreaProductRelation, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsPrefrenceAreaProductRelation), nil
	}
}

func (c cmsPrefrenceAreaProductRelationDo) FindByPage(offset int, limit int) (result []*model.CmsPrefrenceAreaProductRelation, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsPrefrenceAreaProductRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsPrefrenceAreaProductRelationDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsPrefrenceAreaProductRelationDo) Delete(models ...*model.CmsPrefrenceAreaProductRelation) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsPrefrenceAreaProductRelationDo) withDO(do gen.Dao) *cmsPrefrenceAreaProductRelationDo {
	c.DO = *do.(*gen.DO)
	return c
}
