// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall-admin-server/cms/model"
)

func newCmsPrefrenceArea(db *gorm.DB) cmsPrefrenceArea {
	_cmsPrefrenceArea := cmsPrefrenceArea{}

	_cmsPrefrenceArea.cmsPrefrenceAreaDo.UseDB(db)
	_cmsPrefrenceArea.cmsPrefrenceAreaDo.UseModel(&model.CmsPrefrenceArea{})

	tableName := _cmsPrefrenceArea.cmsPrefrenceAreaDo.TableName()
	_cmsPrefrenceArea.ALL = field.NewField(tableName, "*")
	_cmsPrefrenceArea.ID = field.NewInt64(tableName, "id")
	_cmsPrefrenceArea.Name = field.NewString(tableName, "name")
	_cmsPrefrenceArea.SubTitle = field.NewString(tableName, "sub_title")
	_cmsPrefrenceArea.Pic = field.NewBytes(tableName, "pic")
	_cmsPrefrenceArea.Sort = field.NewInt32(tableName, "sort")
	_cmsPrefrenceArea.ShowStatus = field.NewInt32(tableName, "show_status")

	_cmsPrefrenceArea.fillFieldMap()

	return _cmsPrefrenceArea
}

type cmsPrefrenceArea struct {
	cmsPrefrenceAreaDo

	ALL        field.Field
	ID         field.Int64
	Name       field.String
	SubTitle   field.String
	Pic        field.Bytes
	Sort       field.Int32
	ShowStatus field.Int32

	fieldMap map[string]field.Expr
}

func (c cmsPrefrenceArea) Table(newTableName string) *cmsPrefrenceArea {
	c.cmsPrefrenceAreaDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsPrefrenceArea) As(alias string) *cmsPrefrenceArea {
	c.cmsPrefrenceAreaDo.DO = *(c.cmsPrefrenceAreaDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsPrefrenceArea) updateTableName(table string) *cmsPrefrenceArea {
	c.ALL = field.NewField(table, "*")
	c.ID = field.NewInt64(table, "id")
	c.Name = field.NewString(table, "name")
	c.SubTitle = field.NewString(table, "sub_title")
	c.Pic = field.NewBytes(table, "pic")
	c.Sort = field.NewInt32(table, "sort")
	c.ShowStatus = field.NewInt32(table, "show_status")

	c.fillFieldMap()

	return c
}

func (c *cmsPrefrenceArea) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsPrefrenceArea) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["sub_title"] = c.SubTitle
	c.fieldMap["pic"] = c.Pic
	c.fieldMap["sort"] = c.Sort
	c.fieldMap["show_status"] = c.ShowStatus
}

func (c cmsPrefrenceArea) clone(db *gorm.DB) cmsPrefrenceArea {
	c.cmsPrefrenceAreaDo.ReplaceDB(db)
	return c
}

type cmsPrefrenceAreaDo struct{ gen.DO }

func (c cmsPrefrenceAreaDo) Debug() *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsPrefrenceAreaDo) WithContext(ctx context.Context) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsPrefrenceAreaDo) ReadDB() *cmsPrefrenceAreaDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsPrefrenceAreaDo) WriteDB() *cmsPrefrenceAreaDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsPrefrenceAreaDo) Clauses(conds ...clause.Expression) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsPrefrenceAreaDo) Returning(value interface{}, columns ...string) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsPrefrenceAreaDo) Not(conds ...gen.Condition) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsPrefrenceAreaDo) Or(conds ...gen.Condition) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsPrefrenceAreaDo) Select(conds ...field.Expr) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsPrefrenceAreaDo) Where(conds ...gen.Condition) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsPrefrenceAreaDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsPrefrenceAreaDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsPrefrenceAreaDo) Order(conds ...field.Expr) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsPrefrenceAreaDo) Distinct(cols ...field.Expr) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsPrefrenceAreaDo) Omit(cols ...field.Expr) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsPrefrenceAreaDo) Join(table schema.Tabler, on ...field.Expr) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsPrefrenceAreaDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsPrefrenceAreaDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsPrefrenceAreaDo) Group(cols ...field.Expr) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsPrefrenceAreaDo) Having(conds ...gen.Condition) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsPrefrenceAreaDo) Limit(limit int) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsPrefrenceAreaDo) Offset(offset int) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsPrefrenceAreaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsPrefrenceAreaDo) Unscoped() *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsPrefrenceAreaDo) Create(values ...*model.CmsPrefrenceArea) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsPrefrenceAreaDo) CreateInBatches(values []*model.CmsPrefrenceArea, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsPrefrenceAreaDo) Save(values ...*model.CmsPrefrenceArea) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsPrefrenceAreaDo) First() (*model.CmsPrefrenceArea, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsPrefrenceArea), nil
	}
}

func (c cmsPrefrenceAreaDo) Take() (*model.CmsPrefrenceArea, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsPrefrenceArea), nil
	}
}

func (c cmsPrefrenceAreaDo) Last() (*model.CmsPrefrenceArea, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsPrefrenceArea), nil
	}
}

func (c cmsPrefrenceAreaDo) Find() ([]*model.CmsPrefrenceArea, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsPrefrenceArea), err
}

func (c cmsPrefrenceAreaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsPrefrenceArea, err error) {
	buf := make([]*model.CmsPrefrenceArea, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsPrefrenceAreaDo) FindInBatches(result *[]*model.CmsPrefrenceArea, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsPrefrenceAreaDo) Attrs(attrs ...field.AssignExpr) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsPrefrenceAreaDo) Assign(attrs ...field.AssignExpr) *cmsPrefrenceAreaDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsPrefrenceAreaDo) Joins(fields ...field.RelationField) *cmsPrefrenceAreaDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsPrefrenceAreaDo) Preload(fields ...field.RelationField) *cmsPrefrenceAreaDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsPrefrenceAreaDo) FirstOrInit() (*model.CmsPrefrenceArea, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsPrefrenceArea), nil
	}
}

func (c cmsPrefrenceAreaDo) FirstOrCreate() (*model.CmsPrefrenceArea, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsPrefrenceArea), nil
	}
}

func (c cmsPrefrenceAreaDo) FindByPage(offset int, limit int) (result []*model.CmsPrefrenceArea, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsPrefrenceAreaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsPrefrenceAreaDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsPrefrenceAreaDo) Delete(models ...*model.CmsPrefrenceArea) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsPrefrenceAreaDo) withDO(do gen.Dao) *cmsPrefrenceAreaDo {
	c.DO = *do.(*gen.DO)
	return c
}
