// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCmsPrefrenceArea = "cms_prefrence_area"

// CmsPrefrenceArea mapped from table <cms_prefrence_area>
type CmsPrefrenceArea struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	Name       string `gorm:"column:name" json:"name" form:"name"`
	SubTitle   string `gorm:"column:sub_title" json:"subTitle" form:"subTitle"`
	Pic        []byte `gorm:"column:pic" json:"pic" form:"pic"` // 展示图片
	Sort       int32  `gorm:"column:sort" json:"sort" form:"sort"`
	ShowStatus int32  `gorm:"column:show_status" json:"showStatus" form:"showStatus"`
}

// TableName CmsPrefrenceArea's table name
func (*CmsPrefrenceArea) TableName() string {
	return TableNameCmsPrefrenceArea
}
