// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOmsCompanyAddress = "oms_company_address"

// OmsCompanyAddress mapped from table <oms_company_address>
type OmsCompanyAddress struct {
	ID            int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	AddressName   string `gorm:"column:address_name" json:"addressName" form:"addressName"`       // 地址名称
	SendStatus    int32  `gorm:"column:send_status" json:"sendStatus" form:"sendStatus"`          // 默认发货地址：0->否；1->是
	ReceiveStatus int32  `gorm:"column:receive_status" json:"receiveStatus" form:"receiveStatus"` // 是否默认收货地址：0->否；1->是
	Name          string `gorm:"column:name" json:"name" form:"name"`                             // 收发货人姓名
	Phone         string `gorm:"column:phone" json:"phone" form:"phone"`                          // 收货人电话
	Province      string `gorm:"column:province" json:"province" form:"province"`                 // 省/直辖市
	City          string `gorm:"column:city" json:"city" form:"city"`                             // 市
	Region        string `gorm:"column:region" json:"region" form:"region"`                       // 区
	DetailAddress string `gorm:"column:detail_address" json:"detailAddress" form:"detailAddress"` // 详细地址
}

// TableName OmsCompanyAddress's table name
func (*OmsCompanyAddress) TableName() string {
	return TableNameOmsCompanyAddress
}
