// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOmsOrderSetting = "oms_order_setting"

// OmsOrderSetting mapped from table <oms_order_setting>
type OmsOrderSetting struct {
	ID                  int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	FlashOrderOvertime  int32 `gorm:"column:flash_order_overtime" json:"flashOrderOvertime" form:"flashOrderOvertime"`    // 秒杀订单超时关闭时间(分)
	NormalOrderOvertime int32 `gorm:"column:normal_order_overtime" json:"normalOrderOvertime" form:"normalOrderOvertime"` // 正常订单超时时间(分)
	ConfirmOvertime     int32 `gorm:"column:confirm_overtime" json:"confirmOvertime" form:"confirmOvertime"`              // 发货后自动确认收货时间（天）
	FinishOvertime      int32 `gorm:"column:finish_overtime" json:"finishOvertime" form:"finishOvertime"`                 // 自动完成交易时间，不能申请售后（天）
	CommentOvertime     int32 `gorm:"column:comment_overtime" json:"commentOvertime" form:"commentOvertime"`              // 订单完成后自动好评时间（天）
}

// TableName OmsOrderSetting's table name
func (*OmsOrderSetting) TableName() string {
	return TableNameOmsOrderSetting
}
