// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOmsOrderReturnApply = "oms_order_return_apply"

// OmsOrderReturnApply mapped from table <oms_order_return_apply>
type OmsOrderReturnApply struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"`
	OrderID          int64     `gorm:"column:order_id" json:"orderId" form:"orderId"`                             // 订单id
	CompanyAddressID int64     `gorm:"column:company_address_id" json:"companyAddressId" form:"companyAddressId"` // 收货地址表id
	ProductID        int64     `gorm:"column:product_id" json:"productId" form:"productId"`                       // 退货商品id
	OrderSn          string    `gorm:"column:order_sn" json:"orderSn" form:"orderSn"`                             // 订单编号
	CreateTime       time.Time `gorm:"column:create_time" json:"createTime" form:"createTime"`                    // 申请时间
	MemberUsername   string    `gorm:"column:member_username" json:"memberUsername" form:"memberUsername"`        // 会员用户名
	ReturnAmount     float64   `gorm:"column:return_amount" json:"returnAmount" form:"returnAmount"`              // 退款金额
	ReturnName       string    `gorm:"column:return_name" json:"returnName" form:"returnName"`                    // 退货人姓名
	ReturnPhone      string    `gorm:"column:return_phone" json:"returnPhone" form:"returnPhone"`                 // 退货人电话
	Status           int32     `gorm:"column:status" json:"status" form:"status"`                                 // 申请状态：0->待处理；1->退货中；2->已完成；3->已拒绝
	HandleTime       time.Time `gorm:"column:handle_time" json:"handleTime" form:"handleTime"`                    // 处理时间
	ProductPic       string    `gorm:"column:product_pic" json:"productPic" form:"productPic"`                    // 商品图片
	ProductName      string    `gorm:"column:product_name" json:"productName" form:"productName"`                 // 商品名称
	ProductBrand     string    `gorm:"column:product_brand" json:"productBrand" form:"productBrand"`              // 商品品牌
	ProductAttr      string    `gorm:"column:product_attr" json:"productAttr" form:"productAttr"`                 // 商品销售属性：颜色：红色；尺码：xl;
	ProductCount     int32     `gorm:"column:product_count" json:"productCount" form:"productCount"`              // 退货数量
	ProductPrice     float64   `gorm:"column:product_price" json:"productPrice" form:"productPrice"`              // 商品单价
	ProductRealPrice float64   `gorm:"column:product_real_price" json:"productRealPrice" form:"productRealPrice"` // 商品实际支付单价
	Reason           string    `gorm:"column:reason" json:"reason" form:"reason"`                                 // 原因
	Description      string    `gorm:"column:description" json:"description" form:"description"`                  // 描述
	ProofPics        string    `gorm:"column:proof_pics" json:"proofPics" form:"proofPics"`                       // 凭证图片，以逗号隔开
	HandleNote       string    `gorm:"column:handle_note" json:"handleNote" form:"handleNote"`                    // 处理备注
	HandleMan        string    `gorm:"column:handle_man" json:"handleMan" form:"handleMan"`                       // 处理人员
	ReceiveMan       string    `gorm:"column:receive_man" json:"receiveMan" form:"receiveMan"`                    // 收货人
	ReceiveTime      time.Time `gorm:"column:receive_time" json:"receiveTime" form:"receiveTime"`                 // 收货时间
	ReceiveNote      string    `gorm:"column:receive_note" json:"receiveNote" form:"receiveNote"`                 // 收货备注
}

// TableName OmsOrderReturnApply's table name
func (*OmsOrderReturnApply) TableName() string {
	return TableNameOmsOrderReturnApply
}
