// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOmsOrder = "oms_order"

// OmsOrder mapped from table <oms_order>
type OmsOrder struct {
	ID                    int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" form:"id"` // 订单id
	MemberID              int64     `gorm:"column:member_id;not null" json:"memberId" form:"memberId"`
	CouponID              int64     `gorm:"column:coupon_id" json:"couponId" form:"couponId"`
	OrderSn               string    `gorm:"column:order_sn" json:"orderSn" form:"orderSn"`                                            // 订单编号
	CreateTime            time.Time `gorm:"column:create_time" json:"createTime" form:"createTime"`                                   // 提交时间
	MemberUsername        string    `gorm:"column:member_username" json:"memberUsername" form:"memberUsername"`                       // 用户帐号
	TotalAmount           float64   `gorm:"column:total_amount" json:"totalAmount" form:"totalAmount"`                                // 订单总金额
	PayAmount             float64   `gorm:"column:pay_amount" json:"payAmount" form:"payAmount"`                                      // 应付金额（实际支付金额）
	FreightAmount         float64   `gorm:"column:freight_amount" json:"freightAmount" form:"freightAmount"`                          // 运费金额
	PromotionAmount       float64   `gorm:"column:promotion_amount" json:"promotionAmount" form:"promotionAmount"`                    // 促销优化金额（促销价、满减、阶梯价）
	IntegrationAmount     float64   `gorm:"column:integration_amount" json:"integrationAmount" form:"integrationAmount"`              // 积分抵扣金额
	CouponAmount          float64   `gorm:"column:coupon_amount" json:"couponAmount" form:"couponAmount"`                             // 优惠券抵扣金额
	DiscountAmount        float64   `gorm:"column:discount_amount" json:"discountAmount" form:"discountAmount"`                       // 管理员后台调整订单使用的折扣金额
	PayType               int32     `gorm:"column:pay_type" json:"payType" form:"payType"`                                            // 支付方式：0->未支付；1->支付宝；2->微信
	SourceType            int32     `gorm:"column:source_type" json:"sourceType" form:"sourceType"`                                   // 订单来源：0->PC订单；1->app订单
	Status                int32     `gorm:"column:status" json:"status" form:"status"`                                                // 订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单
	OrderType             int32     `gorm:"column:order_type" json:"orderType" form:"orderType"`                                      // 订单类型：0->正常订单；1->秒杀订单
	DeliveryCompany       string    `gorm:"column:delivery_company" json:"deliveryCompany" form:"deliveryCompany"`                    // 物流公司(配送方式)
	DeliverySn            string    `gorm:"column:delivery_sn" json:"deliverySn" form:"deliverySn"`                                   // 物流单号
	AutoConfirmDay        int32     `gorm:"column:auto_confirm_day" json:"autoConfirmDay" form:"autoConfirmDay"`                      // 自动确认时间（天）
	Integration           int32     `gorm:"column:integration" json:"integration" form:"integration"`                                 // 可以获得的积分
	Growth                int32     `gorm:"column:growth" json:"growth" form:"growth"`                                                // 可以活动的成长值
	PromotionInfo         string    `gorm:"column:promotion_info" json:"promotionInfo" form:"promotionInfo"`                          // 活动信息
	BillType              int32     `gorm:"column:bill_type" json:"billType" form:"billType"`                                         // 发票类型：0->不开发票；1->电子发票；2->纸质发票
	BillHeader            string    `gorm:"column:bill_header" json:"billHeader" form:"billHeader"`                                   // 发票抬头
	BillContent           string    `gorm:"column:bill_content" json:"billContent" form:"billContent"`                                // 发票内容
	BillReceiverPhone     string    `gorm:"column:bill_receiver_phone" json:"billReceiverPhone" form:"billReceiverPhone"`             // 收票人电话
	BillReceiverEmail     string    `gorm:"column:bill_receiver_email" json:"billReceiverEmail" form:"billReceiverEmail"`             // 收票人邮箱
	ReceiverName          string    `gorm:"column:receiver_name;not null" json:"receiverName" form:"receiverName"`                    // 收货人姓名
	ReceiverPhone         string    `gorm:"column:receiver_phone;not null" json:"receiverPhone" form:"receiverPhone"`                 // 收货人电话
	ReceiverPostCode      string    `gorm:"column:receiver_post_code" json:"receiverPostCode" form:"receiverPostCode"`                // 收货人邮编
	ReceiverProvince      string    `gorm:"column:receiver_province" json:"receiverProvince" form:"receiverProvince"`                 // 省份/直辖市
	ReceiverCity          string    `gorm:"column:receiver_city" json:"receiverCity" form:"receiverCity"`                             // 城市
	ReceiverRegion        string    `gorm:"column:receiver_region" json:"receiverRegion" form:"receiverRegion"`                       // 区
	ReceiverDetailAddress string    `gorm:"column:receiver_detail_address" json:"receiverDetailAddress" form:"receiverDetailAddress"` // 详细地址
	Note                  string    `gorm:"column:note" json:"note" form:"note"`                                                      // 订单备注
	ConfirmStatus         int32     `gorm:"column:confirm_status" json:"confirmStatus" form:"confirmStatus"`                          // 确认收货状态：0->未确认；1->已确认
	DeleteStatus          int32     `gorm:"column:delete_status;not null" json:"deleteStatus" form:"deleteStatus"`                    // 删除状态：0->未删除；1->已删除
	UseIntegration        int32     `gorm:"column:use_integration" json:"useIntegration" form:"useIntegration"`                       // 下单时使用的积分
	PaymentTime           time.Time `gorm:"column:payment_time" json:"paymentTime" form:"paymentTime"`                                // 支付时间
	DeliveryTime          time.Time `gorm:"column:delivery_time" json:"deliveryTime" form:"deliveryTime"`                             // 发货时间
	ReceiveTime           time.Time `gorm:"column:receive_time" json:"receiveTime" form:"receiveTime"`                                // 确认收货时间
	CommentTime           time.Time `gorm:"column:comment_time" json:"commentTime" form:"commentTime"`                                // 评价时间
	ModifyTime            time.Time `gorm:"column:modify_time" json:"modifyTime" form:"modifyTime"`                                   // 修改时间
}

// TableName OmsOrder's table name
func (*OmsOrder) TableName() string {
	return TableNameOmsOrder
}
